# Generated by Django 5.2.1 on YYYY-MM-DD HH:MM # 実際の日付に置き換えてね
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100, unique=True, verbose_name='キャラクター名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='キャラクター説明')),
                ('prompt_template', models.TextField(verbose_name='プロンプトテンプレート')),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='アイコン画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'AIキャラクター',
                'verbose_name_plural': 'AIキャラクター',
                'ordering': ['character_name'],
            },
        ),
    ]
