# Generated by Django 5.2.1 on YYYY-MM-DD HH:MM # 実際の日付に置き換えてね
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant_app', '0001_initial'), # AICharacterのマイグレーションに依存
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='セッションID')),
                ('message_text', models.TextField(verbose_name='メッセージ内容')),
                ('sender_type', models.CharField(choices=[('user', 'ユーザー'), ('ai', 'AI')], max_length=10, verbose_name='送信者種別')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('ai_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant_app.aicharacter', verbose_name='AIキャラクター')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AI会話履歴',
                'verbose_name_plural': 'AI会話履歴',
                'ordering': ['timestamp'],
            },
        ),
    ]