# Generated by Django 5.2.1 on 2025-05-17 11:15 # 日付は実際のものに合わせてね
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'), # Userモデルのマイグレーションに依存
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('accepted', '承認済み'), ('declined', '拒否済み'), ('blocked', 'ブロック中')], default='pending', max_length=10, verbose_name='関係ステータス')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='応答日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='レコード作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='レコード更新日時')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='被申請者')),
            ],
            options={
                'verbose_name': '友達関係',
                'verbose_name_plural': '友達関係',
                'ordering': ['-requested_at'],
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]