# Generated by Django 5.2.1 on YYYY-MM-DD HH:MM # 実際の日付に置き換えてね
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='場所')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='繰り返しフラグ')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='繰り返しルール')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
                'ordering': ['start_datetime'],
            },
        ),
    ]