# Generated by Django 5.2.1 on 2025-05-27 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('pending', '仮'), ('accepted', '参加'), ('declined', '不参加'), ('tentative', '未定')], default='pending', max_length=10, verbose_name='出欠ステータス')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='主催者フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendar_app.schedule', verbose_name='予定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='参加者ユーザー')),
            ],
            options={
                'verbose_name': '予定参加者',
                'verbose_name_plural': '予定参加者',
                'ordering': ['event__start_datetime', 'user__username'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
