# Generated by Django 4.2.2 on 2025-05-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_eventparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
