# Generated by Django 4.2.2 on 2025-05-28 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_app', '0003_delete_eventparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recurrence_rule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_schedules', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
