# Generated by Django 5.2.1 on YYYY-MM-DD HH:MM # 実際の日付に置き換えてね
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50, verbose_name='通知種別')),
                ('message', models.TextField(verbose_name='通知メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('related_item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='関連アイテムID')),
                ('related_item_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='関連アイテム種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知先ユーザー')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]