# Generated by Django 4.2.2 on 2025-05-28 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0003_delete_eventparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_title', models.CharField(max_length=200, verbose_name='提案タイトル')),
                ('proposed_start_datetime', models.DateTimeField(verbose_name='提案開始日時')),
                ('proposed_end_datetime', models.DateTimeField(verbose_name='提案終了日時')),
                ('proposed_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='提案場所')),
                ('proposed_description', models.TextField(blank=True, null=True, verbose_name='提案詳細（AIからの理由など）')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('accepted', '承認済み'), ('declined', '拒否済み'), ('canceled', 'キャンセル済み')], default='pending', max_length=20, verbose_name='申請ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請作成日時')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='応答日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_schedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='被申請者')),
                ('related_schedule_invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_request_source_invitee', to='calendar_app.schedule', verbose_name='被申請者の関連予定')),
                ('related_schedule_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_request_source_requester', to='calendar_app.schedule', verbose_name='申請者の関連予定')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_schedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '日程調整申請',
                'verbose_name_plural': '日程調整申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
