# Generated by Django 4.2.2 on 2025-05-28 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_app', '0003_delete_eventparticipant'),
        ('schedule_requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleadjustmentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '日程調整/リスケ申請', 'verbose_name_plural': '日程調整/リスケ申請'},
        ),
        migrations.AddField(
            model_name='scheduleadjustmentrequest',
            name='original_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests', to='calendar_app.schedule', verbose_name='リスケジュール対象の元の予定'),
        ),
        migrations.AddField(
            model_name='scheduleadjustmentrequest',
            name='request_type',
            field=models.CharField(choices=[('new', '新規予定'), ('reschedule', 'リスケジュール')], default='new', max_length=20, verbose_name='申請タイプ'),
        ),
        migrations.AlterField(
            model_name='scheduleadjustmentrequest',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_schedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='被申請者 (またはリスケ相手)'),
        ),
        migrations.AlterField(
            model_name='scheduleadjustmentrequest',
            name='proposed_description',
            field=models.TextField(blank=True, null=True, verbose_name='提案詳細（理由など）'),
        ),
    ]
