# Generated by Django 4.2.2 on 2025-05-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_requests_app', '0002_alter_scheduleadjustmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleadjustmentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '日程調整申請', 'verbose_name_plural': '日程調整申請'},
        ),
        migrations.RemoveField(
            model_name='scheduleadjustmentrequest',
            name='original_schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleadjustmentrequest',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='scheduleadjustmentrequest',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_schedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='被申請者'),
        ),
        migrations.AlterField(
            model_name='scheduleadjustmentrequest',
            name='proposed_description',
            field=models.TextField(blank=True, null=True, verbose_name='提案詳細（AIからの理由など）'),
        ),
    ]
