# Generated by Django 5.2.1 on 2025-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_remove_schedule_is_recurring_and_more'),
        ('schedule_requests_app', '0003_alter_scheduleadjustmentrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleadjustmentrequest',
            name='proposed_title',
        ),
        migrations.RemoveField(
            model_name='scheduleadjustmentrequest',
            name='related_schedule_invitee',
        ),
        migrations.RemoveField(
            model_name='scheduleadjustmentrequest',
            name='related_schedule_requester',
        ),
        migrations.AddField(
            model_name='scheduleadjustmentrequest',
            name='related_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_request_source', to='calendar_app.schedule', verbose_name='承認後に作成された予定'),
        ),
        migrations.AddField(
            model_name='scheduleadjustmentrequest',
            name='title_for_invitee',
            field=models.CharField(default=1, max_length=200, verbose_name='被申請者用のタイトル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleadjustmentrequest',
            name='title_for_requester',
            field=models.CharField(default='（仮タイトル）', max_length=200, verbose_name='申請者用のタイトル'),
            preserve_default=False,
        ),
    ]
